#ifndef PCH_H_
#define PCH_H_


#include <SFML/Graphics.hpp>
#include <string.h>
#include <time.h>
#include <iostream>
#include "player.h"
#include "player.cpp"
#include "Bullet.h"
#include "Bullet.cpp"
#include "Enemy.h"
#include "Enemy.cpp"
#include "Invader.h"
#include "Invader.cpp"
#include "Alpha.h"
#include "Alpha.cpp"
#include "menu.h"
#include "game.h"
#include "Beta.h"
#include "Beta.cpp"
#include "Gamma.h"
#include "Gamma.cpp"
#include "Bomb.h"
#include "Bomb.cpp"
#include "AddOns.h"
#include "Lives.h"
#include "Danger.h"
#include "PowerUp.h"
#include "Fire.h"
#include "Monster.h"
#include "Monster.cpp"
#include "Dragon.h"
#include "Dragon.cpp"
#include <SFML/Audio.hpp>
#endif /*PCH_H_*/